### ISSUE TITLE
CW1

### ISSUE THREAD

**Issue by triple666killaz** [oleksandrblazhko/ai201-arestov#15]
Завдання 1
Повага
Для споживача присутні зрозумілі пояснення що таке повага, тому усе зрозуміло
Користувач може сам розуміти повагу інших людей до себе за допомогою того, як він себе почуває у соціумі та за відношенням інших людей до нього

Завдання 2
Мета "Забезпечити доступність отримання естетичного задоволення знаходячись у безпечних умовах, відчуваючи повагу, та слідкуючи за фізичнім станом"

Перший прецедент "надати своє місцезнаходження" наближає користувача пп до досягнення мети тим, що він допомогає системі надати доступ до необхідної інформації

Другий прецедент "надіслати онлайн повідомлення" наближає користувача пп до досягнення мети тим, що він надає інформацію щодо безпеки у регіоні кожні 6 годин

Третїй прецедент "надати найближчі музеї" дозволяє користувачу знайти музей для отримання естетичного задоволення

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
