### ISSUE TITLE
CW2

### ISSUE THREAD

**Issue by triple666killaz** [oleksandrblazhko/ai201-arestov#16]
Завдання 1

1)Порушення атомарності. FR.1.1(Користувач надає ПП своє місцезнаходження) змінемо на користувач надає ПП своє місцезнаходження, емейл, ім'я та пароль

2)Порушення завершенності. FR.2 перетворюємо на:

FR2.1 Користувач надає ПП своє місцезнаходження
FR2.2: Користувач отримує карту з розташуванням найближчих музеїв

3)Порушення безкоштовності реалізації. Перетворимо вимогу 2.1 на "користувач заходить у пп яке пересилає його у інтерфейс google maps та запитує доступ до аккаунту"

**Comment by triple666killaz** [comment]
Завдання 2

1)Розподілена система має вагу 2, бо є розподілений опис архітектури, де кожен сервіс буде відповідати за виконання своїх обовя'зків (компютер з операційною системою, сервер лінукс, монгодб).

2)Спеціальні вимоги до навчання користувачів має вагу 1, бо такий актор, як - Естет-споживач не потребує ніяких складних дій, окрім натискання кнопки надання місцезнаходження тому це не потребує навчання

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
